# Generated by Django 2.0 on 2018-05-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violationid', models.IntegerField(null=True)),
                ('buildingid', models.IntegerField(null=True)),
                ('currentstatusid', models.IntegerField(null=True)),
                ('noticeofviolationid', models.IntegerField(null=True)),
                ('boro', models.TextField()),
                ('housenumber', models.TextField()),
                ('streetname', models.TextField()),
                ('apartment', models.TextField()),
                ('zip', models.TextField()),
                ('story', models.TextField()),
                ('violationclass', models.TextField()),
                ('novdescription', models.TextField()),
                ('currentstatus', models.TextField()),
                ('novtype', models.TextField()),
                ('violationstatus', models.TextField()),
                ('neighborhood', models.TextField()),
                ('inspectiondate', models.DateTimeField()),
                ('approveddate', models.DateTimeField()),
                ('originalcertifybydate', models.DateTimeField()),
                ('originalcorrectbydate', models.DateTimeField()),
                ('newcertifybydate', models.DateTimeField()),
                ('newcorrectbydate', models.DateTimeField()),
                ('certifieddate', models.DateTimeField()),
                ('novissueddate', models.DateTimeField()),
                ('currentstatusdate', models.DateTimeField()),
            ],
        ),
    ]
